# Generated by Django 6.0.2 on 2026-02-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zogospel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musique',
            name='lien_audio',
        ),
        migrations.AddField(
            model_name='musique',
            name='fichier_audio',
            field=models.FileField(blank=True, null=True, upload_to='musique/audio/'),
        ),
    ]
