# Generated by Django 6.0.2 on 2026-02-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zogospel', '0002_remove_musique_lien_audio_musique_fichier_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='musique',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
