# Generated by Django 6.0.2 on 2026-02-11 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zogospel', '0003_actualite_likes_musique_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='region',
            field=models.CharField(choices=[('local', 'Local'), ('afrique', 'Afrique'), ('international', 'International')], default='local', max_length=20),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='zogospel.actualite')),
            ],
        ),
    ]
