# Generated by Django 6.0.2 on 2026-02-11 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zogospel', '0004_actualite_region_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='type_evenement',
            field=models.CharField(choices=[('concert', 'Concert'), ('conference', 'Conférence'), ('showcase', 'Showcase'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('payment_method', models.CharField(choices=[('momo', 'Mobile Money'), ('card', 'Carte Bancaire')], default='momo', max_length=30)),
                ('paid', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='zogospel.agenda')),
            ],
        ),
    ]
