# Generated by Django 6.0.2 on 2026-02-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zogospel', '0005_agenda_type_evenement_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agenda/'),
        ),
    ]
