# Generated by Django 6.0.2 on 2026-02-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zogospel', '0006_agenda_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True)),
                ('accroche', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#8A2BE2', max_length=7)),
                ('icon', models.CharField(default='🎤', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
