# Generated by Django 6.0.2 on 2026-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zogospel', '0007_rubrique'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='magazine/pdfs/'),
        ),
    ]
